### ISSUE TITLE
docker 启动成功但 web 面板拒绝连接

### ISSUE THREAD

**Issue by sgpublic** [gngpp/xunlei#112]
docekr-compose.yaml
```yaml
services:
  xunlei:
    image: gngpp/xunlei:3.11.2-31
    privileged: true
    network_mode: host
    container_name: xunlei
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /approot/etc/xunlei:/opt/data
      - /mnt/download/cache:/downloads
    restart: unless-stopped
```

日志：
```
madray@nas-debian-11:/approot/docker/xunlei$ docker-compose logs xunlei
xunlei  | INFO 2023-09-05 09:57:23: [Asset] LD_LIBRARY_PATH=/var/packages/pan-xunlei-com/target/host/lib
xunlei  | INFO 2023-09-05 09:57:23: [XunleiLauncher] Start Xunlei Pannel UI, listening on 0.0.0.0:5055
xunlei  | INFO 2023-09-05 09:57:23: [Asset] Real path of the symlink /lib64/ld-linux-x86-64.so.2: /var/packages/pan-xunlei-com/target/host/lib/ld-linux-x86-64.so.2
xunlei  | INFO 2023-09-05 09:57:23: [Asset] LD_LIBRARY_PATH=/var/packages/pan-xunlei-com/target/host/lib
xunlei  | INFO 2023-09-05 09:57:23: [XunleiBackendServer] Mount /downloads to /xunlei succeeded
xunlei  | INFO 2023-09-05 09:57:23: [XunleiBackendServer] Start Xunlei Backend Server
xunlei  | INFO 2023-09-05 09:57:23: [XunleiBackendServer] Xunlei Backend Server PID: 58
```
